export const emo = [
  "100","1234","umbrella_with_rain_drops",
  "coffee","aries","taurus","sagittarius","capricorn","aquarius","pisces","anchor",
  "white_check_mark","sparkles","question","grey_question","grey_exclamation",
  "exclamation","heavy_exclamation_mark","heavy_plus_sign","heavy_minus_sign","heavy_division_sign",
  "hash","keycap_star", "telescope", "dove_of_peace", "joy", "train2", "oncoming_police_car", "woman-rowing-boat",
  "zero","one","two","three", "four","five","six","seven","eight","nine","copyright","registered","mahjong",
  "black_joker","a","b","o2","parking","ab","cl","cool","free","id", "new", "traffic_light", "woman-biking",
  "ng","ok","sos","up","vs","flag-ac","flag-ad","flag-ae","flag-af","flag-ag","flag-ai", "bath",
  "flag-al","flag-am","flag-ao","flag-aq","flag-ar","flag-as", "flag-at","flag-au","flag-aw","flag-ax","flag-az",
  "flag-ba","flag-bb","flag-bd","flag-be","flag-bf","flag-bg","flag-bh","flag-bi","flag-bj",
  "flag-bl","flag-bm","flag-bn","flag-bo","flag-bq","flag-br","flag-bs","flag-bt","flag-bv",
  "flag-bw","flag-by","flag-bz","flag-ca","flag-cc","flag-cf","flag-cg","flag-ch","flag-ci","flag-ck",
  "flag-cl","flag-cm","cn","flag-cn","flag-co","flag-cp","flag-cr","flag-cu","flag-cv","flag-cw","flag-cx","flag-cy",
  "flag-cz","de","flag-de","flag-dg","flag-dj","flag-dk","flag-dm","flag-do","flag-dz","flag-ea","flag-ec","flag-ee",
  "flag-eg","flag-eh", "flag-er","es","flag-es","flag-et","flag-eu","flag-fi","flag-fj","flag-fk","flag-fm","flag-fo",
  "fr","flag-fr","flag-ga","gb","uk","flag-gb","flag-gd","flag-ge","flag-gf","flag-gg","flag-gh",
  "flag-gi","flag-gl","flag-gm","flag-gn","flag-gp","flag-gq","flag-gr","flag-gs","flag-gt","flag-gu","flag-gw",
  "flag-gy","flag-hk","flag-hm","flag-hn","flag-hr","flag-ht","flag-hu","flag-ic","flag-id","flag-ie","flag-il",
  "flag-im",
  "flag-in","flag-io","flag-iq","flag-ir","flag-is","it","flag-it","flag-je","flag-jm","flag-jo","jp",
  "flag-jp","flag-ke","flag-kg","flag-kh","flag-ki","flag-km","flag-kn","flag-kp","kr",
  "flag-kr","flag-kw","flag-ky","flag-kz","flag-la","flag-lb","flag-lc","flag-li","flag-lk","flag-lr","flag-ls",
  "flag-lt","flag-lu","flag-lv","flag-ly","flag-ma","flag-mc","flag-md","flag-me","flag-mf","flag-mg","flag-mh",
  "flag-mk","flag-ml","flag-mm","flag-mn","flag-mo","flag-mp","flag-mq","flag-mr","flag-ms","flag-mt","flag-mu",
  "flag-mv",
  "flag-mw","flag-mx","flag-my","flag-mz","flag-na","flag-nc","flag-ne","flag-nf","flag-ng","flag-ni","flag-nl",
  "flag-no","flag-np","flag-nr","flag-nu","flag-nz","flag-om","flag-pa","flag-pe","flag-pf","flag-pg","flag-ph",
  "flag-pk",
  "flag-pl","flag-pm","flag-pn","flag-pr","flag-ps","flag-pt","flag-pw","flag-py","flag-qa","flag-re","flag-ro",
  "flag-rs","ru","flag-ru","flag-rw", "flag-sa","flag-sb","flag-sc","flag-sd","flag-se","flag-sg","flag-sh","flag-si",
  "flag-sj","flag-sk","flag-sl","flag-sm","flag-sn","flag-so","flag-sr","flag-ss","flag-st","flag-sv","flag-sx",
  "flag-sy","flag-sz","flag-ta","flag-tc","flag-td","flag-tf","flag-tg","flag-th","flag-tj","flag-tk","flag-tl",
  "flag-tm","flag-tn","flag-to","flag-tr","flag-tt","flag-tv","flag-tw","flag-tz","flag-ua","flag-ug","flag-um",
  "flag-un","us","flag-us","flag-uy", "flag-uz","flag-va","flag-vc","flag-ve","flag-vg","flag-vi","flag-vn","flag-vu",
  "flag-wf","flag-ws","flag-xk","flag-ye","flag-yt","flag-za","flag-zm", "flag-zw","koko","sa","u7121","u6307",
  "u7981","u7a7a","u5408","u6e80","u6709","u6708","u7533","u5272","u55b6","ideograph_advantage","accept","cyclone",
  "foggy", "closed_umbrella","night_with_stars","sunrise_over_mountains","sunrise","city_sunset","city_sunrise",
  "rainbow","bridge_at_night", "ocean","volcano","milky_way","earth_africa","earth_americas","earth_asia",
  "globe_with_meridians","new_moon","waxing_crescent_moon",
  "moon","waxing_gibbous_moon","full_moon","waning_gibbous_moon","last_quarter_moon","waning_crescent_moon",
  "crescent_moon","new_moon_with_face",
  "first_quarter_moon_with_face","last_quarter_moon_with_face","full_moon_with_face","sun_with_face","star2",
  "stars", "thermometer",
  "mostly_sunny", "sun_small_cloud","barely_sunny","sun_behind_cloud","partly_sunny_rain","sun_behind_rain_cloud",
  "rain_cloud",
  "snow_cloud","lightning","lightning_cloud","tornado","tornado_cloud","fog","wind_blowing_face","hotdog","taco",
  "burrito","chestnut",
  "seedling","evergreen_tree","deciduous_tree","palm_tree","cactus","hot_pepper","tulip","cherry_blossom","rose",
  "female-teacher",
  "hibiscus","sunflower","blossom","corn","ear_of_rice","herb","four_leaf_clover","maple_leaf","fallen_leaf",
  "female-singer",
  "female-technologist", "leaves","mushroom","tomato", "grapes","melon","watermelon","tangerine","lemon",
  "banana","pineapple","apple",
  "green_apple", "female-student", "pear","peach","cherries","strawberry","hamburger","pizza","meat_on_bone",
  "poultry_leg",
  "rice_cracker","rice_ball","rice","curry","ramen","spaghetti", "bread","fries","sweet_potato","dango","oden","sushi",
  "fried_shrimp",
  "fish_cake","icecream","shaved_ice","ice_cream","doughnut","cookie", "chocolate_bar","candy","lollipop","custard",
  "honey_pot","cake",
  "bento","stew","fried_egg","cooking","fork_and_knife","tea","sake","wine_glass", "football","rugby_football",
  "woman-swimming",
  "man-swimming","swimmer","woman-lifting-weights","man-lifting-weights","weight_lifter","woman-golfing"
  ,"man-golfing","golfer","racing_motorcycle","racing_car","cricket_bat_and_ball","volleyball",
  "field_hockey_stick_and_ball",
  "ice_hockey_stick_and_puck","mouse2","ox","water_buffalo","cow2","tiger2","leopard","rabbit2","cat2","dragon",
  "crocodile","whale2","snail","snake","racehorse","ram","goat", "sheep","monkey","rooster","chicken","dog2",
  "pig2","boar",
  "elephant","octopus","shell","bug","ant","bee","honeybee","beetle","fish","tropical_fish",
  "blowfish","turtle","hatching_chick","baby_chick","hatched_chick","bird","penguin","koala","poodle","dromedary_camel",
  "camel","dolphin","flipper", "mouse","cow","tiger","rabbit","cat","dragon_face","whale","horse","monkey_face","dog",
  "pig","frog","hamster","wolf","bear","panda_face","pig_nose","feet","paw_prints","chipmunk","eyes",
  "eye-in-speech-bubble",
  "eye","ear","nose","lips","tongue","point_up_2","point_down","point_left", "church","mountain",
  "umbrella_on_ground","fountain",
  "golf","ferry","boat","sailboat","skier","ice_skate","woman-bouncing-ball","man-bouncing-ball"
  ,"person_with_ball","tent","fuelpump","scissors","airplane","email","envelope","fist","hand","raised_hand","v",
  "writing_hand","pencil2","black_nib","heavy_check_mark","heavy_multiplication_x","latin_cross","star_of_david",
  "eight_spoked_asterisk","eight_pointed_black_star","snowflake","sparkle","x","negative_squared_cross_mark",
  "heavy_heart_exclamation_mark_ornament","heart","arrow_right","curly_loop","loop", "arrow_heading_up",
  "arrow_heading_down",
  "arrow_left","arrow_up","arrow_down","black_large_square","white_large_square",
  "star","o","wavy_dash","part_alternation_mark","congratulations", "secret", "chains","no_entry",
  "shinto_shrine","church","mountain","umbrella_on_ground","fountain","golf","ferry","boat",
  "sailboat","skier","ice_skate","woman-bouncing-ball", "heavy_multiplication_x","latin_cross",
  "star_of_david","eight_spoked_asterisk", "eight_pointed_black_star","snowflake","sparkle","x",
  "negative_squared_cross_mark","heavy_heart_exclamation_mark_ornament",
  "heart","arrow_right","curly_loop","loop","arrow_heading_up","arrow_heading_down","arrow_left","arrow_up",
  "arrow_down","black_large_square","white_large_square","star","o","wavy_dash","part_alternation_mark",
  "congratulations","secret",
]
